- README.md
Change theme name `Halo Theme Ha` to `Halo Theme Hao`.
> Rectify theme name

- package.json
- theme.yaml
2. 侧栏分类长度设置
3. 自定义文章导航栏及其他路径
4. 添加公安备案设置
5. fix 不能修改 banner 名称的问题
> 1. 侧栏标签长度设置

- templates/modules/widgets/aside/categories.html
- templates/modules/widgets/aside/tags.html
> 修复 侧边栏配置的“分类”和“标签”模块

- templates/assets/zhheo/custom.css
- templates/modules/head.html
- 引入 font-awesome 字体图标
- 修复代码块阴影&纯黑色背景
- banner 背面字体图标“->”大小及位置
- 自我介绍渐变色背景
- 文章页列表样式及缩进
> 引入自定义CSS样式文件，修复若干Bug。

- templates/assets/zhheo/custom.css
> 修复prism.js 代码高亮 背景颜色出错

- settings.yaml
> docs: 更新 文章-动态主色 的说明文字

- templates/modules/post-list.html
- templates/modules/widgets/top-group.html
> fix: 修复推荐文章和文章列表的图片重复问题

- templates/modules/post-list.html
> fix: 一个月内时间显示xx天前，其余显示日期 #78

- templates/category.html
- templates/modules/post-list.html
- templates/modules/widgets/aside/recent-posts.html
- templates/tag.html
https://github.com/liuzhihang/halo-theme-hao/issues/80
> fix: 分类、Tag、recent-posts的随机图片问题

- templates/archives.html
- templates/assets/zhheo/zhheoblog.css
- templates/category.html
- templates/modules/head.html
- templates/modules/post-list.html
- templates/modules/widgets/page.html
- templates/tag.html
> feat: 归档页以及分页

- templates/assets/js/halo.js
- templates/assets/zhheo/rightmenu.js
- templates/links.html
- templates/modules/head.html
- templates/page.html
- templates/post.html
新建了 `templates/assets/js/halo.js` 文件用户存放 Halo版主题自己的js方法
Fix #55
> fix: Halo评论组件暗色模式

- templates/modules/layouts/layout.html
- templates/modules/widgets/top-group.html
> fix: 默认参数造成的主页布局不整齐 

- templates/modules/sidebar.html
> fix: 修复手机端侧栏专栏没用text的问题

- templates/modules/right-menu.html
> fix: 修复右键菜单随便逛逛点击无效的问题 

- templates/modules/sidebar.html
> fix: 更新手机端侧栏相关字段名称

- templates/archives.html
- templates/categories.html
- templates/category.html
- templates/index.html
- templates/links.html
- templates/modules/aside.html
- templates/modules/bar/category.html
- templates/modules/bar/custom-category.html
- templates/modules/bar/custom-tag.html
- templates/modules/bar/custom-url.html
- templates/modules/bar/tag.html
- templates/modules/layouts/layout.html
- templates/modules/nav.html
- templates/modules/post-list.html
- templates/modules/recent-top.html
- templates/modules/widgets/aside/stat.html
- templates/modules/widgets/aside/tags-stat.html
- templates/modules/widgets/aside/tags.html
- templates/page.html
- templates/post.html
- templates/tag.html
- templates/tags.html
> chore: Fragment 引用模板的语法升级

- templates/modules/head.html
> fix: 修复 主题样式配置 默认配色

- templates/assets/js/main.js
- templates/assets/zhheo/blogex.js
- templates/assets/zhheo/custom.css
- templates/assets/zhheo/zhheoblog.css
你好，我最近正在使用这款主题，好看是真滴好看。
我希望可以帮助它变得更好，代码没有大动，主要就是解决我标题里提到的内容，希望可以早点儿被采纳，或者有什么更好的建议可以跟我说。
> 1、解决主页文章列表摘要信息不显示；2、解决文章内代码块内容溢出；3、屏蔽主页鼠标滚动时控制台频繁报错

- settings.yaml
- templates/assets/zhheo/zhheoblog.css
- templates/modules/post-list.html
- templates/modules/widgets/aside/comments.html
- templates/post.html
Fix:最新评论
Fix:优化上一页下一页 阅读建议
Fix:修复文章摘要显示错位
Feat:限制文章摘要是否显示
> 修复最新评论,文章摘要，优化上下页阅读建议

- settings.yaml
- templates/assets/zhheo/zhheoblog.css
- templates/modules/post-list.html
- templates/modules/widgets/aside/comments.html
- templates/post.html
Fix:最新评论
Fix:优化上一页下一页 阅读建议
Fix:修复文章摘要显示错位
Feat:限制文章摘要是否显示
> 修复最新评论,优化上下页,首页摘要错位

- templates/modules/widgets/aside/comments.html
> 修复最新评论切换获取

- templates/assets/zhheo/rightmenu.js
- templates/modules/right-menu.html
- templates/modules/widgets/cardNewestComments.html
- templates/modules/widgets/console.html
Reverts liuzhihang/halo-theme-hao#226
> Revert "修复最近评论错误；修复无右键菜单切换深浅色模式错误；"

- settings.yaml
- templates/about.html
- templates/assets/libs/canvas/dark.js
- templates/assets/zhheo/zhheoblog.css
- templates/modules/layouts/layout.html
- templates/modules/postHeadAiDescription.html
- templates/modules/widgets/aside/contain/archive-contain.html
- templates/modules/widgets/aside/contain/stat-contain.html
- templates/modules/widgets/aside/tags-stat.html
- templates/modules/widgets/console.html
> 文章ai摘要修复，错误提示

- settings.yaml
- templates/404.html
- templates/about.html
- templates/fcircle.html
- templates/links.html
- templates/modules/commentBarrage.html
- templates/modules/footer.html
- templates/modules/head.html
- templates/modules/layouts/layout.html
- templates/modules/twikoo.html
- templates/modules/widgets/aside/comments.html
- templates/modules/widgets/cardNewestComments.html
- templates/modules/widgets/top-group.html
- templates/moments.html
- templates/page.html
- templates/post.html
添加今日推荐小标题可编辑，
其他设置-添加动态标题
Twikoo评论-同时最多显示弹幕数可编辑，弹幕显示间隔时间ms可编辑
> 添加今日推荐小标题可编辑， 其他设置-添加动态标题 Twikoo评论-同时最多显示弹幕数可编辑，弹幕显示间隔时间ms可编辑

- settings.yaml
> fix: 添加个人信息内容数量最大最小值，放置填写数量不够导致500

- settings.yaml
- templates/about.html
- templates/assets/js/heo.js
- templates/assets/js/main.js
- templates/assets/zhheo/commentBarrage.js
- templates/assets/zhheo/zhheoblog.css
- templates/categories.html
- templates/fcircle.html
- templates/links.html
- templates/modules/commentBarrage.html
- templates/modules/footer.html
- templates/modules/head.html
- templates/modules/layouts/layout.html
- templates/modules/postHeadAiDescription.html
- templates/modules/right-menu.html
- templates/modules/twikoo.html
- templates/modules/widgets/about-widgets/authorCareers.html
- templates/modules/widgets/about-widgets/like-music.html
- templates/modules/widgets/about-widgets/personalities-photo.html
- templates/modules/widgets/about-widgets/statistics-map.html
- templates/modules/widgets/aside/comments.html
- templates/modules/widgets/aside/profile.html
- templates/modules/widgets/aside/wechat.html
- templates/modules/widgets/banner-group.html
- templates/modules/widgets/cardNewestComments.html
- templates/modules/widgets/console.html
- templates/modules/widgets/nav-right.html
- templates/music.html
- templates/post.html
- theme.yaml
> 静态资源优化,友联-默认样式右侧图标

- settings.yaml
> docs: 修改了Twikoo评论系统的部分设置提示词

- README.md
- settings.yaml
- templates/assets/css/fullPage.css
- templates/bangumis.html
- templates/equipment.html
- templates/modules/header/index-img.html
- templates/moments.html
- templates/todolist.html
- theme.yaml
参考：[我的装备|张洪Heo](https://blog.zhheo.com/equipment/)
为Hao添加我的装备页面模版
更新追番页评论组件
添加预览网站
> 添加我的装备页面模版

- settings.yaml
- templates/album.html
- templates/modules/head.html
- templates/photos.html
- theme.yaml
> 新增相册集页面模板，适配图库插件

- settings.yaml
- templates/comments.html
- templates/fcircle.html
- templates/modules/comment/commentBarrage.html
- templates/modules/comment/twikoo.html
- templates/modules/common/common-script.html
- templates/modules/widgets/aside/comments.html
- templates/modules/widgets/cardNewestComments.html
> 为留言板页面添加弹窗,优化部分配置项无需输入反引号

- settings.yaml
- templates/assets/js/heo.js
- templates/assets/zhheo/custom.css
- templates/modules/widgets/aside/music.html
- templates/modules/widgets/aside/steam.html
- templates/modules/widgets/aside/welcome.html
> 侧边栏添加Steam卡片,音乐卡片

- templates/modules/widgets/aside/comments.html
- templates/modules/widgets/console.html
> 修复最近评论中出现友链|非文章评论的报错问题

- templates/error/404.html
- templates/error/500.html
> 修复500页和404页报错的问题

- templates/error/404.html
- templates/error/500.html
> 更新500页和404页的nav title

- settings.yaml
修复了一个用户引导方面的bug
在halo后台 外观-主题-关于的小部件提示有误
statistics-map（数据统计&【音乐偏好】）
【】中的不应该是音乐偏好，应该是地图位置
> 修复了一个用户引导方面的bug

- templates/assets/js/halo.js
- templates/assets/zhheo/blogex.js
- templates/modules/variables/site-config.html
> fix: 修复waline最近评论未自动定位到该评论的位置上

- settings.yaml
- templates/modules/widgets/aside/profile.html
> `侧边栏`-`个人信息`中新增背景图

- templates/modules/widgets/about-widgets/about-reward.html
- templates/modules/widgets/about-widgets/statistics-map.html
* 修复“关于”页面中“地图”中的圆角问题 https://github.com/liuzhihang/halo-theme-hao/issues/597
> 修复“关于”页面中“地图”中的圆角问题

- templates/about.html
fix: 修复"关于"页面中“十年”进度超过100%的显示问题
> fix: 修复"关于"页面中“十年”进度超过100%的显示问题

- templates/assets/js/main.js
- templates/assets/js/utils.js
> 修复页面加载 /null 这一不存在的资源的问题

- templates/assets/zhheo/zhheoblog.css
> 修复分隔线不显示的问题

- settings.yaml
- templates/about.html
- templates/modules/variables/site-config.html
- templates/modules/widgets/about-widgets/about-reward.html
- theme.yaml
* change: "十年之约"进度小于10%不显示进度值
* change: 关于（赞赏）标记功能变更为统一配置
> change: "十年之约"进度小于10%不显示进度值

- settings.yaml
- templates/post.html
> 添加最后更新时间显示配置

- templates/assets/zhheo/zhheoblog.css
- templates/modules/widgets/about-widgets/about-reward.html
- templates/modules/widgets/banner-group.html
- theme.yaml
* fix: 修复侧边栏“赞赏”间距问题
* change: 优化移动端情况下左侧banner只显示前2个
* change: 优化关于（赞赏）样式
> fix: 修复侧边栏“赞赏”间距问题

- theme.yaml
Update theme.yaml
https://liuzhihang.com/upload/logo.jpg
> Fix logo 502 error

- templates/assets/zhheo/zhheoblog.css
- templates/index.html
> 修复首页顶部横幅移动端兼容问题

- README.md
> delete: 删除失效预览站点

- settings.yaml
- templates/assets/zhheo/zhheoblog.css
- templates/modules/footer.html
- templates/modules/widgets/banner-group.html
- theme.yaml
change: 首页顶部banner标题支持不超过122px长度的文字
change: 支持自定义页脚padding高度
add: 支持切换首页左侧banner滚动样式
> change: 首页顶部banner标题支持不超过122px长度的文字

- settings.yaml
- templates/assets/zhheo/zhheoblog.css
change: 调整首页"技术栈"滚动倾斜角度
fix: 修复图库顶部背景图设置
> 调整首页"技术栈"滚动倾斜角度

- settings.yaml
- templates/assets/js/halo.js
- templates/modules/variables/site-config.html
- templates/modules/widgets/aside/power.html
- theme.yaml
fix: 修复侧边栏爱发电用户访问地址错误问题
change: 修改主题侧边栏爱发电设置，需要重新根据提示进行设置
change: 变更侧边栏爱发电功能访问地址支持手动修改
> fix: 修复侧边栏爱发电用户访问地址错误问题

- settings.yaml
- templates/assets/css/fmoments.css
- templates/assets/js/fmoments.js
- templates/friends.html
- theme.yaml
rt，新增朋友圈页面。
在 友链 设置页面新增两个设置，需配合该 PR 实现：https://github.com/chengzhongxue/plugin-friends-new/pull/5
支持触底加载更多，相关 `css` 和 `js` 均在访问 朋友圈 页面才会加载。
**效果图如下:**
> feat: 新增朋友圈页面
